services:
  env_helper:
    build:
      context: ./projects/env_helper
    volumes:
      - type: bind
        source: ${PWD}/.env321
        target: /code/.env
    profiles:
      - create-env
  env_validator:
    build:
      context: ./projects/env_validator
    environment:
      - VK_KATE_TOKEN=${VK_KATE_TOKEN}
      - VK_OFFICIAL_TOKEN=${VK_OFFICIAL_TOKEN}
      - VK_COMMUNITY_ID=${VK_COMMUNITY_ID}
      - VK_COMMUNITY_TOKEN=${VK_COMMUNITY_TOKEN}
      - VK_SERVER_TITLE=${VK_SERVER_TITLE}
      - SERVER_URL=${SERVER_URL}
      - TGM_API_ID=${TGM_API_ID}
      - TGM_API_HASH=${TGM_API_HASH}
      - TGM_BOT_TOKEN=${TGM_BOT_TOKEN}
      - TGM_BOT_SESSION=${TGM_BOT_SESSION}
      - TGM_CLIENT_PHONE=${TGM_CLIENT_PHONE}
      - TGM_CLIENT_SESSION=${TGM_CLIENT_SESSION}
      - TGM_CHANNEL_ID=${TGM_CHANNEL_ID}
      - TGM_PL_CHANNEL_ID=${TGM_PL_CHANNEL_ID}
      - VTT_LANGUAGE=${VTT_LANGUAGE}
      - VTT_IGNORE_ADS=${VTT_IGNORE_ADS}
  redis:
    image: redis:7.2.3-alpine3.19
    restart: always
    healthcheck:
      test: sh -c "redis-cli ping | grep PONG"
      interval: 1s
      timeout: 3s
      retries: 5
    depends_on:
      env_validator:
        condition: service_completed_successfully
  cb_receiver:
    build:
      context: ./projects/cb_receiver
      additional_contexts:
        - libs=./libs
    restart: always
    environment:
      - VK_COMMUNITY_ID=${VK_COMMUNITY_ID}
      - VK_COMMUNITY_TOKEN=${VK_COMMUNITY_TOKEN}
      - VK_SERVER_TITLE=${VK_SERVER_TITLE}
      - SERVER_URL=${SERVER_URL}
      - VTT_IGNORE_ADS=${VTT_IGNORE_ADS}
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_RESULT_BACKEND=redis://redis/0
    depends_on:
      env_validator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
  worker_main:
    build:
      context: ./projects/worker
      additional_contexts:
        - libs=./libs
    restart: always
    command: celery -A app.main worker -n worker-main -Q vtt-wall -c 1 -l INFO
    environment:
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_RESULT_BACKEND=redis://redis/0
      - VK_KATE_TOKEN=${VK_KATE_TOKEN}
      - VK_OFFICIAL_TOKEN=${VK_OFFICIAL_TOKEN}
      - TGM_API_ID=${TGM_API_ID}
      - TGM_API_HASH=${TGM_API_HASH}
      - TGM_BOT_TOKEN=${TGM_BOT_TOKEN}
      - TGM_BOT_SESSION=${TGM_BOT_SESSION}
      - TGM_CHANNEL_ID=${TGM_CHANNEL_ID}
      - TGM_PL_CHANNEL_ID=${TGM_PL_CHANNEL_ID}
      - VTT_LANGUAGE=${VTT_LANGUAGE}
      - VTT_IGNORE_ADS=${VTT_IGNORE_ADS}
    depends_on:
      env_validator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
  worker_pl:
    build:
      context: ./projects/worker
      additional_contexts:
        - libs=./libs
    command: celery -A app.main worker -n worker-pl -Q vtt-playlist -c 1 -l INFO
    environment:
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_RESULT_BACKEND=redis://redis/0
      - VK_KATE_TOKEN=${VK_KATE_TOKEN}
      - VK_OFFICIAL_TOKEN=${VK_OFFICIAL_TOKEN}
      - TGM_API_ID=${TGM_API_ID}
      - TGM_API_HASH=${TGM_API_HASH}
      - TGM_BOT_TOKEN=${TGM_BOT_TOKEN}
      - TGM_BOT_SESSION=${TGM_BOT_SESSION}
      - TGM_CHANNEL_ID=${TGM_CHANNEL_ID}
      - TGM_PL_CHANNEL_ID=${TGM_PL_CHANNEL_ID}
      - VTT_LANGUAGE=${VTT_LANGUAGE}
      - VTT_IGNORE_ADS=${VTT_IGNORE_ADS}
    depends_on:
      env_validator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    profiles:
      - with-pl
  tgm_bot:
    build:
      context: ./projects/tgm_bot
      additional_contexts:
        - libs=./libs
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_RESULT_BACKEND=redis://redis/0
      - VK_KATE_TOKEN=${VK_KATE_TOKEN}
      - VK_OFFICIAL_TOKEN=${VK_OFFICIAL_TOKEN}
      - TGM_API_ID=${TGM_API_ID}
      - TGM_API_HASH=${TGM_API_HASH}
      - TGM_BOT_TOKEN=${TGM_BOT_TOKEN}
      - TGM_BOT_SESSION=${TGM_BOT_SESSION}
      - TGM_CLIENT_PHONE=${TGM_CLIENT_PHONE}
      - TGM_CLIENT_SESSION=${TGM_CLIENT_SESSION}
      - TGM_CHANNEL_ID=${TGM_CHANNEL_ID}
      - TGM_PL_CHANNEL_ID=${TGM_PL_CHANNEL_ID}
      - VTT_LANGUAGE=${VTT_LANGUAGE}
    depends_on:
      env_validator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:8080"
    environment:
      - NGINX_PROXY_PASS=http://cb_receiver:8000
    depends_on:
      cb_receiver:
        condition: service_started
