x-env-file: &env-file
  - path: .env
    required: false
  # For Portainer
  - path: stack.env
    required: false

volumes:
  html:
  acme:
services:
  env_validator:
    build:
      context: projects/env_validator
      additional_contexts:
        libs: ./libs
    env_file: *env-file
  redis:
    image: redis:7.2.3-alpine3.19
    restart: always
    healthcheck:
      test: sh -c "redis-cli ping | grep PONG"
      interval: 1s
      timeout: 3s
      retries: 5
    depends_on:
      env_validator:
        condition: service_completed_successfully
  cb_receiver:
    build:
      context: projects/cb_receiver
      additional_contexts:
        libs: ./libs
    restart: always
    env_file: *env-file
    environment:
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_RESULT_BACKEND=redis://redis/0

      # SSL envs
      - VIRTUAL_HOST=${NGINX_SERVER_NAME}
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=${NGINX_SERVER_NAME}
    depends_on:
      env_validator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
  worker_main:
    build:
      context: projects/worker
      additional_contexts:
        libs: ./libs
    restart: always
    command: celery -A app.main worker -n worker-main -Q vtt-wall -c 1 -l INFO
    env_file: *env-file
    environment:
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_RESULT_BACKEND=redis://redis/0
    depends_on:
      env_validator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
  worker_pl:
    build:
      context: projects/worker
      additional_contexts:
        libs: ./libs
    command: celery -A app.main worker -n worker-pl -Q vtt-playlist -c 1 -l INFO
    env_file: *env-file
    environment:
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_RESULT_BACKEND=redis://redis/0
    depends_on:
      env_validator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    profiles:
      - with-pl
  tgm_bot:
    build:
      context: projects/tgm_bot
      additional_contexts:
        libs: ./libs
    restart: always
    env_file: *env-file
    environment:
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_RESULT_BACKEND=redis://redis/0
    depends_on:
      env_validator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
  nginx:
    build:
      context: ./nginx
    ports:
      - "${NGINX_HTTP_PORT:-80}:8080"
    environment:
      - NGINX_PROXY_PASS=http://cb_receiver:8000
    depends_on:
      cb_receiver:
        condition: service_started
    profiles:
      - http
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.9.0-alpine
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    profiles:
      - https
  nginx-proxy-acme:
    image: nginxproxy/acme-companion:2.6.1
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${SSL_EMAIL}
    profiles:
      - https
      - acme
