version: 1
formatters:
    default:
        (): uvicorn.logging.DefaultFormatter
        fmt: '%(levelprefix)s %(asctime)-8s %(name)-15s %(message)s'
        use_colors: None
    file:
        format: '%(levelname)s %(asctime)-8s %(name)-15s %(message)s'
    access:
        (): uvicorn.logging.AccessFormatter
        fmt: '%(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
handlers:
    default:
        formatter: default
        class: logging.StreamHandler
        stream: ext://sys.stderr
    access:
        formatter: access
        class: logging.StreamHandler
        stream: ext://sys.stdout
    app_default:
        formatter: default
        class: logging.StreamHandler
    rotating_file:
        formatter: file
        filename: logs/vtt-cb-receiver.log
        maxBytes: 1000000
        backupCount: 5
        class: logging.handlers.RotatingFileHandler
loggers:
    uvicorn: 
        handlers: [default, rotating_file] 
        level: INFO
    uvicorn.error:
        level: INFO
    uvicorn.access: 
        handlers": [access, rotating_file] 
        level: INFO
        propagate: False
    app:
        handlers: [app_default, rotating_file]
        level: INFO